const matches = [
  {
    id: 1,
    date: "2024-09-01",
    localTeam: "Boca Juniors",
    visitorTeam: "River Plate",
    img_localTeam: "boca.png",
    img_visitorTeam: "riber.png",
  },
  {
    id: 2,
    date: "2024-09-01",
    localTeam: "Independiente",
    visitorTeam: "Racing Club",
    img_localTeam: "independiente.png",
    img_visitorTeam: "racing.png",
  },
  {
    id: 3,
    date: "2024-09-02",
    localTeam: "San Lorenzo",
    visitorTeam: "Huracán",
    img_localTeam: "san_lorenzo.png",
    img_visitorTeam: "huracan.png",
  },
  {
    id: 4,
    date: "2024-09-02",
    localTeam: "Newell's Old Boys",
    visitorTeam: "Rosario Central",
    img_localTeam: "newells.png",
    img_visitorTeam: "rosario_central.png",
  },
  {
    id: 5,
    date: "2024-09-03",
    localTeam: "Estudiantes",
    visitorTeam: "Gimnasia y Esgrima La Plata",
    img_localTeam: "estudiantes.png",
    img_visitorTeam: "gimnasia.png",
  },
  {
    id: 6,
    date: "2024-09-03",
    localTeam: "Barracas Central",
    visitorTeam: "Instituto",
    img_localTeam: "colon.png",
    img_visitorTeam: "barracas_central.png",
  },
  {
    id: 7,
    date: "2024-09-04",
    localTeam: "Lanús",
    visitorTeam: "Banfield",
    img_localTeam: "lanus.png",
    img_visitorTeam: "banfield.png",
  },
  {
    id: 8,
    date: "2024-09-04",
    localTeam: "Vélez Sarsfield",
    visitorTeam: "Platense",
    img_localTeam: "velez.png",
    img_visitorTeam: "platense.png",
  },
  {
    id: 9,
    date: "2024-09-05",
    localTeam: "Atlético Tucumán",
    visitorTeam: "Tigre",
    img_localTeam: "atl_tucuman.png",
    img_visitorTeam: "tigre.png",
  },
  {
    id: 10,
    date: "2024-09-05",
    localTeam: "Godoy Cruz",
    visitorTeam: "Ind. Rivadavia",
    img_localTeam: "godoy_cruz.png",
    img_visitorTeam: "ind_rivadavia.png",
  },
  {
    id: 11,
    date: "2024-09-06",
    localTeam: "Talleres",
    visitorTeam: "Belgrano",
    img_localTeam: "talleres.png",
    img_visitorTeam: "belgrano.png",
  },
  {
    id: 12,
    date: "2024-09-06",
    localTeam: "Riestra",
    visitorTeam: "Central Cordoba",
    img_localTeam: "riestra.png",
    img_visitorTeam: "central_cba.png",
  },
  {
    id: 13,
    date: "2024-09-07",
    localTeam: "Sarmiento",
    visitorTeam: "Defensa y Justicia",
    img_localTeam: "sarmiento.png",
    img_visitorTeam: "def_justicia.png",
  },
];

export default matches;
